# Continuous Integration/Delivery PR - Web (Firebase hosting)
name: Flutter CI - Web Firebase Deploy on PR

'on': pull_request



jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - uses: actions/checkout@v2
      
      - name: Download Dependencies
        run: flutter pub get
        working-directory: homeworks/cleandex_poketecture

      - name: Static analysis on the sources
        run: flutter analyze
        working-directory: homeworks/cleandex_poketecture

      - name: Run all tests
        run: flutter test
        working-directory: homeworks/cleandex_poketecture
        
      - name: Build flutter web app
        run: flutter build web
        working-directory: homeworks/cleandex_poketecture

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: "./homeworks/cleandex_poketecture" 
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLEANDEX_POKETECTURE }}'
          projectId: cleandex-poketecture
