# Continuous Integration/Delivery on release branch - Web (Firebase hosting)
name: Flutter CI - Web Firebase Deploy on release creation

'on':
  push:
    branches:
      - release
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - uses: actions/checkout@v2

      - name: Download Dependencies
        run: flutter pub get
        working-directory: homeworks/cleandex_poketecture

      - name: Build flutter web app
        run: flutter build web
        working-directory: homeworks/cleandex_poketecture

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: "./homeworks/cleandex_poketecture" 
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLEANDEX_POKETECTURE }}'
          channelId: live
          projectId: cleandex-poketecture
